apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: paymentservice-reader-binding
  namespace: online-boutique

subjects:
  - kind: ServiceAccount
    name: paymentservice-sa
    namespace: online-boutique

roleRef:
  kind: Role
  name: paymentservice-reader
  apiGroup: rbac.authorization.k8s.io