apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend
  namespace: online-boutique
data:
  PORT: "8080"
  PRODUCT_CATALOG_SERVICE_ADDR: "productcatalogservice:3550"
  CURRENCY_SERVICE_ADDR: "currencyservice:7000"
  CART_SERVICE_ADDR: "cartservice:7070"
  RECOMMENDATION_SERVICE_ADDR: "recommendationservice:8080"
  SHIPPING_SERVICE_ADDR: "shippingservice:50051"
  CHECKOUT_SERVICE_ADDR: "checkoutservice:5050"
  AD_SERVICE_ADDR: "adservice:9555"
  #SHOPPING_ASSISTANT_SERVICE_ADDR: "shoppingassistantservice:80"
  ENABLE_PROFILER: "0"
  ENV_PLATFORM: "local"
  #ENABLE_ASSISTANT: "false"
  FRONTEND_MESSAGE: "This is a Portfolio project for a local Kubernetes Cluster by Alireza Hoseini"
  #PACKAGING_SERVICE_URL: ""
  #CYMBAL_BRANDING: "false"
  # As part of an optional Google Cloud demo, you can run an optional microservice called the "packaging service".
  #PACKAGING_SERVICE_URL: "" # This value would look like "http://123.123.123"