apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitlab-ci
  namespace: online-boutique

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gitlab-ci
  namespace: online-boutique
rules:
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch", "patch", "update"]

  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gitlab-ci
  namespace: online-boutique
subjects:
  - kind: ServiceAccount
    name: gitlab-ci
    namespace: online-boutique
roleRef:
  kind: Role
  name: gitlab-ci
  apiGroup: rbac.authorization.k8s.io